### ISSUE TITLE
Nan check for floats is not available

### ISSUE THREAD

**Issue by CFoltin** [zeroSteiner/rule-engine#80]
Hi,

thanks for the engine! 
We encountered an issue checking a float (e.g. YEAR) for being nan. The intuitive check YEAR == nan isn't working (pythonic way of treating nan, because nan == nan is false), but there is no math.isnan() or similar method or attribute present like in native python.

We ended up using YEAR.to_str == 'nan' which is not that nice.

**Comment by zeroSteiner** [comment]
Yean Nan does not equal Nan per the IEEE spec as I recall. A `is_nan` attribute for FLOAT values might do the trick here. I could add that pretty easily.

**Comment by zeroSteiner** [comment]
I added this in the [v4.3.0](https://github.com/zeroSteiner/rule-engine/releases/tag/v4.3.0) release.

The build automation ran into a minor issue though so 4.3.0 was never posted to PyPi. The build automation issue was fixed in 4.3.1 which is available on [PyPi](https://pypi.org/project/rule-engine/4.3.1/).
